export type ReduxActionType = {
  REQUESTED: string
  SUCCEEDED: string
  FAILED: string
  DEBOUNCED?: string
}

const FETCH_POST_ACTION: ReduxActionType = {
  REQUESTED: 'FETCH_POST_REQUESTED',
  SUCCEEDED: 'FETCH_POST_SUCCEEDED',
  FAILED: 'FETCH_POST_FAILED',
}

const FETCH_KEYBS_ACTION: ReduxActionType = {
  REQUESTED: 'FETCH_KEYB_REQUESTED',
  SUCCEEDED: 'FETCH_KEYB_SUCCEEDED',
  FAILED: 'FETCH_KEYB_FAILED',
}

const FETCH_PARTS_ACTION: ReduxActionType = {
  REQUESTED: 'FETCH_PARTS_REQUESTED',
  SUCCEEDED: 'FETCH_PARTS_SUCCEEDED',
  FAILED: 'FETCH_PARTS_FAILED',
}

const FETCH_TEMPLATES_ACTION: ReduxActionType = {
  REQUESTED: 'FETCH_TEMPLATES_REQUESTED',
  SUCCEEDED: 'FETCH_TEMPLATES_SUCCEEDED',
  FAILED: 'FETCH_TEMPLATES_FAILED',
}

const FETCH_PROFILE_ACTION: ReduxActionType = {
  REQUESTED: 'FETCH_PROFILE_REQUESTED',
  SUCCEEDED: 'FETCH_PROFILE_SUCCEEDED',
  FAILED: 'FETCH_PROFILE_FAILED',
}

const FETCH_SEARCH_POSTS_SUGGESTIONS_ACTION: ReduxActionType = {
  REQUESTED: 'FETCH_SEARCH_POSTS_REQUESTED',
  SUCCEEDED: 'FETCH_SEARCH_POSTS_SUCCEEDED',
  FAILED: 'FETCH_SEARCH_POSTS_FAILED',
  DEBOUNCED: 'FETCH_SEARCH_POSTS_DEBOUNCED',
}

const FETCH_EVENTS: ReduxActionType = {
  REQUESTED: 'FETCH_EVENTS_REQUESTED',
  SUCCEEDED: 'FETCH_EVENTS_SUCCEDED',
  FAILED: 'FETCH_EVENTS_FAILED',
}

const ReduxActionTypes = {
  FETCH_POST: FETCH_POST_ACTION,
  FETCH_KEYBS: FETCH_KEYBS_ACTION,
  FETCH_PARTS: FETCH_PARTS_ACTION,
  FETCH_TEMPLATES: FETCH_TEMPLATES_ACTION,
  FETCH_PROFILE: FETCH_PROFILE_ACTION,
  FETCH_SEARCH_POSTS_SUGGESTIONS: FETCH_SEARCH_POSTS_SUGGESTIONS_ACTION,
  FETCH_EVENTS: FETCH_EVENTS,
}

export default ReduxActionTypes
